name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          bash -c "source venv/bin/activate && pip install -r requirements.txt"

      - name: Run tests
        run: |
          bash -c "source venv/bin/activate && pytest"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@161.35.68.159 << EOF
          cd /root/CD-Winc
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          systemctl restart flask_app
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}